services:
    backend:
        build:
            context: ./backend
        container_name: url-checker-backend
        ports:
            - '3000:3000'

    frontend:
        build:
            context: ./frontend
            args:
                VITE_API_URL: ${VITE_API_URL}
        container_name: url-checker-frontend
        ports:
            - '5173:80'
        depends_on:
            - backend
